### ISSUE TITLE
Cannot get my notifications back

### ISSUE THREAD

**Issue by sphh** [CarlosACepeda/LiveDisplay#48] opened 2020-06-21 12:15 UTC
**Describe the bug**
I put an app to the blacklist, so that no notifications are displayed. Now I cannot find a way to get these blacklisted notification back.

**To Reproduce**
1. Go to `Settings > Notification > Blacklist`
2. Click on the app, which notifications you want to change
3. Tick `Blacklisted`
4. The app's notification are not displayed in `LiveDisplay` **and** the native lock screen
5. Go again to Settings > Notification > Blacklist`
6. Click on the app, which notifications you want to change
7. `Blacklisted` is not ticked, so it cannot be unticked
8. Remove the `LiveDisplay` app
9. The notifications are missing from the native lock screen
10. Go to `Settings > Apps & Notifications` and click on the app, which notifications you want to get back
11. Go to `App notifications`
12. Click on each notification and then on `On lock screen` (in Advanced section)
13. You will see, that this settings are still set to `Show all notification content`

**Expected behavior**
1. I would expect the blacklist to have a way to disable an app (have the checkbox to remember the ticked status, so that it can be unticked again)
2. I would expect the `LiveDisplay` to reset these setting when uninstalled
3. I would expect that I am able to re-enable notifications on the native lock screen by standard procedures (see 10-13) 

**Smartphone:**
 - Device: Unihertz Jelly Pro
 - OS: Android 8.1
 - Version of the app: Latest from Play store

**Additional context**
Please tell me how to get my notifications on the native lock screen back! (I can use `adb`, if that's needed)

**Comment by CarlosACepeda** [comment] 2020-06-24 15:40
Can you tell me the specific application you blacklisted? I can't reproduce the bug, :/

**Comment by sphh** [comment] 2020-06-24 15:46
The app where I observed this behaviour is [NetGuard](https://www.netguard.me/).

**Comment by CarlosACepeda** [comment] 2020-06-24 16:17
Try to delete LiveDisplay's storage and cache before uninstalling.
I've tested and it works properly!
Also be sure that the app is really deleted. Sometimes it won't let you uninstall it because it is a device administrator!
Please tell me how it goes. :))

**Comment by CarlosACepeda** [comment] 2020-06-24 16:23
And if for some reason it still doesn't work, try this command on adb:

adb shell pm clear com.underground.livedisplay   --> It deletes all the shared preferences. (along with all the data xd) (I use the shared preferences to save the current state of an specific app, and use those values to block or delete the app's notification, I suspect that it gets stuck for some reason retrieving the current block level for Netguard and it gets blocked forever (maybe that's why when you click the app in the Blacklisted apps screen it doesn't appear as blacklisted))

If you want to check the source code here it is:

[Where the notification gets blocked](https://github.com/CarlosACepeda/LiveDisplay/blob/c0e65f706bdc2df0ca0ae55aea9b27a1091b687c/LiveDisplay/Servicios/Notificaciones/CatcherHelper.cs#L81)

[Where I recover the current block status of an app](https://github.com/CarlosACepeda/LiveDisplay/blob/c0e65f706bdc2df0ca0ae55aea9b27a1091b687c/LiveDisplay/Servicios/Blacklist/Blacklist.cs#L27)

**Comment by CarlosACepeda** [comment] 2020-06-27 19:01
Did it work? :))

**Comment by sphh** [comment] 2020-06-29 13:34
Unfortunately no. I installed / deinstalled the app and sent the commands:
```
$ adb devices
List of devices attached
ABCDEFGHIJKLMNOP	device

$ adb shell
Jelly-Pro:/ $ pm clear com.underground.livedisplay
Failed
1|Jelly-Pro:/ $
```
The same, if I send it in one go:
```
$ adb shell pm clear com.underground.livedisplay
Failed
```

**Comment by CarlosACepeda** [comment] 2020-06-30 14:26
This is weird, however, you must know that the only way the app can stop/block notifications is if the Notification Listener is active (if Livedisplay has access to notifications, see screenshot), disable it and the blacklist will stop working, because all the notifications related functionality depends entirely on this Notification Listener, the functionality of the app won't persist after a uninstall, so if this keeps happening after you've done the steps, I'll close the issue, because I can't reproduce the bug either. :/



![Screenshot_20200630-091829](https://user-images.githubusercontent.com/21343483/86137597-1441f280-bab3-11ea-9e4b-eb9fba838936.png)

**Comment by sphh** [comment] 2020-06-30 17:55
Thank you for your support.

I reconsidered my question and noticed, that we might talk about different things... My fault, if I was not clear enough.

I do see the notifications in the swipe-down menu. That's not the problem. What I don't see, are the notifications on Android's lock screen. These are the notification which disappeared. I think that happened since I installed `LiveDisplay`, but I also tried `AcDisplay` at the same time. Since only `LiveDisplay` had the configurable option to not display notification on its screen, I thought it this happened when I played with `LiveDisplay`.

Anyway, I am talking about the notifications on Android's default lock screen. This can be disabled with the following sequence:
![Screenshot_20200630-192743](https://user-images.githubusercontent.com/4856462/86159910-8e499a00-bafa-11ea-8d6e-9961c23ddf8f.png)
Click on `App notifications`
![Screenshot_20200630-192756](https://user-images.githubusercontent.com/4856462/86159958-a15c6a00-bafa-11ea-85d1-2872dcb85e93.png)
Click on `Running services` (and not the checkbox on the right side)
![Screenshot_20200630-192812](https://user-images.githubusercontent.com/4856462/86160011-b2a57680-bafa-11ea-9e95-39b8166c7506.png)
Here you can see, that `On the lock screen` `Show[s] all notification content`. That was the setting I changed in `LiveDisplay` and since then I cannot get it back - even if has the setting as shown in the screenshot...

**Comment by CarlosACepeda** [comment] 2020-06-30 18:43
Okay, thanks for clearing that up, 
the notifications that appear on the Notification drawer are the same ones that appear on the Android's default lockscreen.
So, I think this is a won't fix, because it is now out of the application's scope, because as I told you the notifications are the same, whether they are on the Notification drawer or on the Android lockscreen, and I, as a developer can't control that either through my app.😕 
If you think it's a mistake I can reopen the issue but for now I don't see where LiveDisplay fits in this entire situation. 😁

**Closed as completed by CarlosACepeda** 2020-06-30 18:43 UTC
Labels: invalid
